# Generated by Django 6.0.7 on 2026-08-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='岗位名称')),
            ],
            options={
                'verbose_name': '岗位',
                'verbose_name_plural': '岗位',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('days', models.IntegerField(verbose_name='本月天数')),
                ('shifts', models.JSONField(default=list, verbose_name='班次列表')),
                ('shift_demand', models.JSONField(default=dict, verbose_name='每班每天人数')),
                ('role_reqs', models.JSONField(default=dict, verbose_name='岗位人数条件')),
                ('min_shift_target', models.IntegerField(default=18, verbose_name='最少出勤班数')),
                ('exempt_names', models.JSONField(default=list, verbose_name='豁免人员名单')),
                ('rest_block', models.JSONField(default=dict, verbose_name='连休规则')),
                ('work_window', models.JSONField(default=dict, verbose_name='工作窗口')),
                ('worker_snapshot', models.JSONField(default=list, verbose_name='人员快照')),
                ('status', models.CharField(default='', max_length=20, verbose_name='求解状态')),
                ('message', models.CharField(default='', max_length=255, verbose_name='结果说明')),
                ('diagnostics', models.JSONField(default=list, verbose_name='诊断信息')),
                ('result_json', models.JSONField(default=dict, verbose_name='排班结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '排班记录',
                'verbose_name_plural': '排班记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='姓名')),
                ('roles', models.ManyToManyField(blank=True, related_name='persons', to='scheduler.role', verbose_name='岗位')),
            ],
            options={
                'verbose_name': '人员',
                'verbose_name_plural': '人员',
            },
        ),
    ]
