# Generated by Django 6.0.7 on 2026-08-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='required_shifts',
            field=models.IntegerField(default=0, help_text='本月应上班班数（每人班次要求，0 表示使用全局最少班数）', verbose_name='应上班数'),
        ),
        migrations.AddField(
            model_name='person',
            name='worked_so_far',
            field=models.IntegerField(default=0, help_text='本月已上班班数（排班时会补足 应上班数 - 已上班数）', verbose_name='已上班数'),
        ),
    ]
