# Generated by Django 6.0.7 on 2026-08-20 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_person_required_shifts_person_worked_so_far'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='班组名称')),
            ],
            options={
                'verbose_name': '班组',
                'verbose_name_plural': '班组',
            },
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['team__name', 'name'], 'verbose_name': '人员', 'verbose_name_plural': '人员'},
        ),
        migrations.AddField(
            model_name='person',
            name='default_shift',
            field=models.CharField(choices=[('早班', '早班'), ('中班', '中班'), ('晚班', '晚班')], default='早班', max_length=10, verbose_name='默认班次'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='daily_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='每天下井总人数'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='周期开始日期'),
        ),
        migrations.AlterField(
            model_name='person',
            name='worked_so_far',
            field=models.IntegerField(default=0, help_text='导入时的已上班数（排班后按日期自动累计）', verbose_name='已上班数'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='days',
            field=models.IntegerField(verbose_name='周期天数'),
        ),
        migrations.AddField(
            model_name='person',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='scheduler.team', verbose_name='班组'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='scheduler.team', verbose_name='班组'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(verbose_name='周期内第几天（0 起）')),
                ('shift', models.CharField(blank=True, default='', max_length=10, verbose_name='班次')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='scheduler.person', verbose_name='人员')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='scheduler.schedule', verbose_name='排班')),
            ],
            options={
                'verbose_name': '排班明细',
                'verbose_name_plural': '排班明细',
                'unique_together': {('schedule', 'person', 'day')},
            },
        ),
    ]
