# Generated by Django 6.0.7 on 2026-08-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_team_alter_person_options_person_default_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='daily_headcount',
            field=models.IntegerField(default=0, verbose_name='该班应上人数（每天）'),
        ),
        migrations.AddField(
            model_name='team',
            name='exempt_names',
            field=models.JSONField(default=list, verbose_name='豁免人员'),
        ),
        migrations.AddField(
            model_name='team',
            name='min_shift_target',
            field=models.IntegerField(default=18, verbose_name='每人应上最少班数'),
        ),
        migrations.AddField(
            model_name='team',
            name='rest_block',
            field=models.JSONField(default=dict, verbose_name='连休范围'),
        ),
        migrations.AddField(
            model_name='team',
            name='role_reqs',
            field=models.JSONField(default=dict, verbose_name='固定岗位应上人数'),
        ),
    ]
