# Generated by Django 6.0.7 on 2026-08-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_group_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True, help_text='禁用的人员不参与排班（但仍保留在人员列表里）', verbose_name='是否启用'),
        ),
    ]
