# Generated by Django 6.0.7 on 2026-08-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_remove_schedule_result_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='shift_demand',
            field=models.JSONField(default=dict, verbose_name='每班每天人数'),
        ),
    ]
