# Generated by Django 6.0.7 on 2026-09-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_team_shift_demand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='work_window',
        ),
    ]
