# Generated by Django 6.0.7 on 2026-09-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_remove_schedule_work_window'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['schedule', 'day'], name='assign_sched_day_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['person', 'schedule'], name='assign_person_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['team', 'is_active'], name='person_team_active_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['team', 'year', 'month'], name='sched_team_ym_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['-created_at'], name='sched_created_idx'),
        ),
    ]
