# Generated by Django 6.0.7 on 2026-09-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_assignment_assign_sched_day_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='role',
            field=models.CharField(blank=True, default='', help_text='按什么岗位上班就记什么岗位；岗位约束之外的补位人员记「普通」', max_length=50, verbose_name='当天实际岗位'),
        ),
    ]
