# Generated by Django 5.2.17 on 2026-09-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_assignment_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='person_overrides',
            field=models.JSONField(default=dict, verbose_name='专人专项约束'),
        ),
        migrations.AddField(
            model_name='team',
            name='person_overrides',
            field=models.JSONField(default=dict, verbose_name='专人专项约束'),
        ),
    ]
