# Generated by Django 5.2.17 on 2026-09-10 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_schedule_person_overrides_team_person_overrides'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='short_name',
        ),
    ]
