# Generated by Django 5.2.17 on 2026-09-10 11:26
"""删除「每班每天人数」相关内容。

`Team.shift_demand` / `Schedule.shift_demand` 是早期为「按每班人数排班」预留的字段，
但排班逻辑与界面从未使用它（生成排班只读 `Team.daily_headcount`），属于死字段，故删除。
删除前库中数据：Team 全部为空 dict；Schedule 仅 1 条为历史调试数据，其余为空 dict。
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_remove_group_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='shift_demand',
        ),
        migrations.RemoveField(
            model_name='team',
            name='shift_demand',
        ),
    ]
